### ISSUE TITLE
CURL Class not found 

### ISSUE THREAD

**Issue by sameer615** [stymiee/authnetjson#2]
Hii 

Im using authnet
when i run /examples/aim/createTransactionRequest_authCapture.php file ....

giving an error

Class 'Curl\Curl' not found in src\authnet\AuthnetApiFactory.php on line 63

**Comment by stymiee** [comment]
Did you run a composer install when setting up the package?

**Comment by sameer615** [comment]
yes... and problem resolved used another payment gateway .... thanks BTW
