### ISSUE TITLE
Compatibility with latest Authorize.net Changes

### ISSUE THREAD

**Issue by DevinWalker** [stymiee/authnetjson#8]
Hi there!

Thanks for creating such a great library for Authnet. I'm wondering, do you have plans to update the APIs now that AIM and other APIs are deprecated?

Will this library continue to work as expected with the following changes?

https://support.authorize.net/s/article/Authorize-Net-Network-Change-FAQ
https://support.authorize.net/s/article/Recurring-Billing-Flag-Rebill-Feature-End-of-Life-Overview

**Comment by stymiee** [comment]
Everything in this package will continue to work as expected despite the changes and deprecations on Authorize.Net's side. One thing I should do is change the code to no longer use the Akamai name. But that won't change how anything works. I'm also going to leave SIM support in the package until it is officially disabled by Authorize.Net.
