### ISSUE TITLE
Webhook returned as not valid if apache_request_headers isn't defined

### ISSUE THREAD

**Issue by ericnicolaas** [stymiee/authnetjson#9]
The `getAllHeaders()` method in `AuthnetWebhook` provides a workaround for situations where `apache_request_headers()` isn't defined, but it's incorrect. 

```
protected function getAllHeaders()
    {
        if (function_exists('apache_request_headers')) {
            $headers = apache_request_headers();
        } else {
            $headers = array_filter($_SERVER, function($key) {
                return strpos($key, 'HTTP_') === 0;
            }, ARRAY_FILTER_USE_KEY);
        }
        return $headers;
    }
```

The headers array when using the non-Apache method is different to the Apache version. For one, all the header keys start with HTTP_ and they also use underscores instead of dashes. i.e.

HTTP_X_ANET_SIGNATURE instead of X-ANET-SIGNATURE

Hence, the `isset()` check in `isValid()` fails.

**Comment by stymiee** [comment]
Thank you for submitting this fix. It will be in a new release soon.

**Comment by ericnicolaas** [comment]
Thanks for the quick response @stymiee!
